### PR TITLE
device: Allow for unset pool property

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Review by wallyworld — APPROVED** [review]
Change looks great, thank you. Can we update/add a unit test to catch this scenario?

**Comment by stgraber** [comment]
@wallyworld that would probably be a good idea but I have no idea how the testsuite works in this project, already took me quite a while to even track down what needed relaxing for this fix :)

It kinda looks like you have a mocked MAAS server which doesn't behave the way MAAS actually does, so maybe all you need to do is fix that part so that it fails without this branch?

**Comment by wallyworld** [comment]
Superseded by #81

**Comment by wallyworld** [comment]
@stgraber i added a test in a new pr and will land that

**Pull request closed without merging**
